'use client';
import { useEffect, useState } from 'react';
import ConnectedApps from './ConnectedApps';
import ProductEditor, { blankProduct } from './ProductEditor';
import { api, Translate } from './api';
const call = (body?: any) => api('connected-apps', body ? 'POST' : 'GET', body);
export default function PriceConnections({ t }: { t: Translate }) {
  const [rows, setRows] = useState<any[]>([]); const [page, setPage] = useState(0); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const [edit, setEdit] = useState<any>(); const [search, setSearch] = useState(''); const [matches, setMatches] = useState<any[]>([]);
  const load = async () => { try { setRows((await api(`connected-apps?incoming=1&page=${page}`)).rows); } catch (e) { setError((e as Error).message); } };
  useEffect(() => { void load(); }, [page]);
  useEffect(() => { let active = true; api(`connected-apps?search=${encodeURIComponent(search)}`).then(r => { if (active) setMatches(r.rows); }).catch(e => setError(e.message)); return () => { active = false; }; }, [search]);
  const review = async (p: any, v: any) => { setBusy(true); setError(''); try { await call({ action: 'review', id: p.id, revision: p.revision, ...v }); setEdit(undefined); await load(); } catch (e) { setError((e as Error).message); throw e; } finally { setBusy(false); } };
  return <><ConnectedApps call={call} /><section><h2>Incoming Products</h2><p>Review product specifications before creating or linking an item. Accounting approval is not part of this review.</p>{error && <p role="alert">{error}</p>}<button onClick={load}>Refresh queue</button>
    <label>Find existing product / reusable item<input value={search} onChange={e => setSearch(e.target.value)} /></label>
    {rows.map(p => <article key={p.id} style={{ border: '1px solid #cbd5e1', padding: 12, margin: '12px 0' }}><h3>{p.data.item.code || 'Code missing'} · {p.data.item.description}</h3><p>{p.data.item.brand} · {p.data.item.specifications} · {p.data.item.unit}</p><p>{p.data.note} · {p.status} · {p.result.reason}</p>
      {p.status === 'PENDING_REVIEW' && <><button disabled={busy} onClick={() => setEdit(p)}>Create regular product</button>
        <details><summary>Create reusable custom item</summary><form onSubmit={e => { e.preventDefault(); const f = Object.fromEntries(new FormData(e.currentTarget)); void review(p, { decision: 'APPROVED', type: 'REUSABLE', custom: { reference: f.reference, description: f.description, unit: f.unit, suggestedUnitPrice: f.price }, reason: f.reason, pricingConfirmed: true }).catch(() => {}); }}>{[['reference','Reference',p.data.item.code],['description','Description',p.data.item.description],['unit','Unit',p.data.item.unit],['price','Suggested unit price',''],['reason','Review reason','']].map(([name,label,value]) => <label key={name} style={{ display: 'block' }}>{label}<input name={name} defaultValue={value} required={name !== 'reference'} /></label>)}<label><input type="checkbox" required />I confirmed the product and its suggested price</label><button disabled={busy}>Approve reusable item</button></form></details>
        <form onSubmit={e => { e.preventDefault(); const f = new FormData(e.currentTarget); const [type,targetId] = String(f.get('target')).split(':'); void review(p, { decision: 'LINKED', type, targetId, reason: f.get('reason') }).catch(() => {}); }}><label>Link existing product<select name="target" required><option value="">Choose matching product (use search above)</option>{matches.map(m => <option key={`${m.type}:${m.id}`} value={`${m.type}:${m.id}`}>{m.code} · {m.description} · {m.unit} ({m.type})</option>)}</select></label><input name="reason" required placeholder="Evidence that specifications match" /><button disabled={busy}>Link existing</button></form>
        <form onSubmit={e => { e.preventDefault(); const f = new FormData(e.currentTarget); void review(p, { decision: f.get('decision'), reason: f.get('reason') }).catch(() => {}); }}><select name="decision"><option value="CHANGES_REQUESTED">Request changes</option><option value="REJECTED">Reject</option></select><input name="reason" required placeholder="Reason / correction needed" /><button disabled={busy}>Send decision</button></form>
      </>}
    </article>)}<button disabled={!page} onClick={() => setPage(page - 1)}>Previous</button><span> Page {page + 1} </span><button disabled={rows.length < 100} onClick={() => setPage(page + 1)}>Next</button>
    {edit && <><p>Enter current pricing and confirm it by saving. Values are never taken from the workflow proposal.</p><ProductEditor t={t} initial={{ ...blankProduct, partNumber: edit.data.item.code, description: edit.data.item.description, brand: edit.data.item.brand, unit: edit.data.item.unit, cost: '', listPrice: '0', details: { ...blankProduct.details, detailedDescription: edit.data.item.specifications, specifications: [] } }} onClose={() => setEdit(undefined)} actionBusy={busy} onSave={product => review(edit, { decision: 'APPROVED', type: 'PRODUCT', product, pricingConfirmed: true, reason: 'Administrator reviewed product specifications and entered pricing' })} /></>}
  </section></>;
}
