'use client';
import {useState} from 'react';
import {api,type Translate} from '../api';
import {DNDialog} from './controls';
import {fields,fieldNames,detectMapping,displayDate} from '../../shared/dn-tracker';
export default function ImportDialog({upload,reports,reportId,t,close,saved}: {upload:any;reports:any[];reportId:string;t:Translate;close:()=>void;saved:(id:string)=>void}) {
 const [sheet,setSheet]=useState(0),[header,setHeader]=useState(0),[mapping,setMapping]=useState(detectMapping(upload.sheets[0].rows[0]||[])),[dateOrder,setDateOrder]=useState('DMY'),[name,setName]=useState(upload.filename.replace(/\.[^.]+$/,'')),[date,setDate]=useState(new Date().toISOString().slice(0,10)),[target,setTarget]=useState(reportId),[preview,setPreview]=useState<any>(),[ack,setAck]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const changeSheet=(index:number,row=0)=>{setSheet(index);setHeader(row);setMapping(detectMapping(upload.sheets[index].rows[row]||[]));setPreview(null);};
 const run=async(task:()=>Promise<void>)=>{setBusy(true);setError('');try{await task();}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 return <DNDialog title={t('Review delivery-note import','مراجعة استيراد أذونات التسليم')} close={()=>!busy&&close()} wide>
  {error&&<div className="notice error" role="alert">{error}</div>}
  <div className="dn-filter-grid"><label>{t('Replace report','استبدال التقرير')}<select disabled={!!preview} value={target} onChange={e=>setTarget(e.target.value)}><option value="">{t('Create new report','إنشاء تقرير جديد')}</option>{reports.filter(r=>!r.archived).map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label>{!target&&<label>{t('Report name','اسم التقرير')}<input disabled={!!preview} value={name} onChange={e=>setName(e.target.value)}/></label>}<label>{t('Report date','تاريخ التقرير')}<input disabled={!!preview} type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>{t('Worksheet','ورقة العمل')}<select value={sheet} onChange={e=>changeSheet(Number(e.target.value))}>{upload.sheets.map((s:any,i:number)=><option key={i} value={i}>{s.name}</option>)}</select></label><label>{t('Header row','صف العناوين')}<input type="number" min="1" max="101" value={header+1} onChange={e=>changeSheet(sheet,Math.max(0,Number(e.target.value)-1))}/></label><label>{t('Source text dates','تواريخ النص في المصدر')}<select value={dateOrder} onChange={e=>{setDateOrder(e.target.value);setPreview(null);}}><option value="DMY">DD-MM-YYYY</option><option value="MDY">MM-DD-YYYY</option><option value="ISO">YYYY-MM-DD</option></select></label></div>
  <p>{t('Dates display as DD-MM-YYYY. Excel date/time cells are normalized automatically.','تظهر التواريخ بتنسيق DD-MM-YYYY ويتم توحيد خلايا تاريخ ووقت Excel تلقائياً.')}</p>
  <div className="dn-filter-grid">{fields.map(k=><label key={k}>{t(...fieldNames[k])}<select value={mapping[k]} onChange={e=>{setMapping({...mapping,[k]:Number(e.target.value)});setPreview(null);}}><option value="-1">{t('Not mapped','غير مرتبط')}</option>{(upload.sheets[sheet].rows[header]||[]).map((h:string,i:number)=><option key={i} value={i}>{i+1}. {h}</option>)}</select></label>)}</div>
  <div className="table-scroll"><table><thead><tr>{upload.sheets[sheet].rows[header]?.map((h:string,i:number)=><th key={i}>{h}</th>)}</tr></thead><tbody>{upload.sheets[sheet].rows.slice(header+1,header+5).map((r:string[],i:number)=><tr key={i}>{r.map((v,j)=><td key={j}>{j===mapping.date?displayDate(v):v}</td>)}</tr>)}</tbody></table></div>
  <button disabled={busy} onClick={()=>void run(async()=>{setPreview(await api('dn-tracker/preview','POST',{reportId:target||undefined,name,filename:upload.filename,reportDate:date,header,dateOrder,mapping,rows:upload.sheets[sheet].rows}));setAck(false);})}>{t('Preview changes','معاينة التغييرات')}</button>
  {preview&&<div className="dn-import-summary"><h3>{t('Import comparison','مقارنة الاستيراد')}</h3><p>{preview.comparison.customers} {t('customers','عملاء')} · {preview.comparison.notes} {t('DNs','أذونات')} · {preview.comparison.rows} {t('rows','صفوف')}</p>{[['added','Added','مضاف'],['changed','Changed','متغير'],['missing','Absent in replacement','غائب عن النسخة الجديدة'],['resolvedChanged','Resolved notes requiring review','أذونات منتهية المتابعة تحتاج مراجعة']].map(([k,en,ar])=><details key={k}><summary>{t(en,ar)}: {preview.comparison[k].length}</summary><p>{preview.comparison[k].join(', ')||'—'}</p></details>)}{!!preview.comparison.ambiguous.length&&<div className="notice">{t('Customer name variants found. Confirm these represent the same customer before importing.','تم العثور على صيغ مختلفة لأسماء العملاء. تأكد أنها لنفس العميل قبل الاستيراد.')}<pre>{JSON.stringify(preview.comparison.ambiguous,null,2)}</pre></div>}{preview.issues.length>0&&<div className="notice error"><h4>{t('Correct these source rows and upload again','صحح الصفوف التالية في المصدر ثم أعد الرفع')}</h4>{preview.issues.slice(0,100).map((i:any,n:number)=><p key={n}>{i.row}: {i.message}</p>)}</div>}<label><input type="checkbox" checked={ack} onChange={e=>setAck(e.target.checked)}/>{t('I reviewed the changes. Missing notes do not imply invoicing.','راجعت التغييرات. غياب الأذونات لا يعني فوترتها.')}</label><button className="primary" disabled={busy||!ack||!!preview.issues.length} onClick={()=>void run(async()=>{const result=await api('dn-tracker/commit/'+preview.id,'POST',{acknowledge:ack});saved(result.id);})}>{t('Confirm replacement','تأكيد الاستيراد')}</button></div>}
 </DNDialog>;
}
