'use client';
import {useState} from 'react';
import {api} from '../api';
import {showConfirm} from '../confirm';
import {DNDialog,CustomerPicker} from './controls';
export default function SharedViews({meta,directory,filters,t,close,refresh,initial}:any) {
 const [draft,setDraft]=useState<any>(initial),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function run(task:()=>Promise<void>){setBusy(true);setError('');try{await task();refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <DNDialog title={t('Shared presets & customer groups','العروض المحفوظة ومجموعات العملاء')} close={close}>{error&&<p className="notice error" role="alert">{error}</p>}<div className="actions"><button onClick={()=>setDraft({kind:'GROUP',name:'',customers:[]})}>{t('New customer group','مجموعة عملاء جديدة')}</button><button onClick={()=>setDraft({kind:'PRESET',name:'',content:filters})}>{t('Save current view','حفظ العرض الحالي')}</button></div>{meta.views.map((v:any)=><article className="dn-saved-view" key={v.id}><strong>{v.name}</strong><small>{v.kind==='GROUP'?t('Customer group','مجموعة عملاء'):t('Preset','عرض محفوظ')}</small><div className="actions"><button onClick={()=>setDraft({...v,customers:v.content.customers||[]})}>{t('Edit','تعديل')}</button><button onClick={()=>setDraft({...v,id:undefined,version:undefined,name:v.name+' '+t('Copy','نسخة'),customers:v.content.customers||[]})}>{t('Duplicate','نسخ')}</button><button disabled={busy} onClick={()=>void run(async()=>{if(await showConfirm(t('Delete this shared view?','حذف هذا العرض المشترك؟'))){await api('dn-tracker/views/'+v.id,'DELETE',{version:v.version});}})}>{t('Delete','حذف')}</button></div></article>)}{draft&&<div className="dn-view-editor"><label>{t('Name','الاسم')}<input value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label>{draft.kind==='GROUP'?<CustomerPicker label={t('Group customers','عملاء المجموعة')} customers={directory.customers} value={draft.customers} onChange={(customers:any)=>setDraft({...draft,customers})}/>:<><p>{t('Saved filters and sorting','المرشحات والترتيب المحفوظة')}</p><CustomerPicker label={t('Include customers','تضمين العملاء')} customers={directory.customers} value={draft.content.include||[]} onChange={(include:any)=>setDraft({...draft,content:{...draft.content,include}})}/><CustomerPicker label={t('Exclude customers','استبعاد العملاء')} customers={directory.customers} value={draft.content.exclude||[]} onChange={(exclude:any)=>setDraft({...draft,content:{...draft.content,exclude}})}/><button onClick={()=>setDraft({...draft,content:filters})}>{t('Replace with current filters','استبدال بالمرشحات الحالية')}</button></>}<button disabled={busy||!draft.name.trim()} onClick={()=>void run(async()=>{await api('dn-tracker/views'+(draft.id?'/'+draft.id:''),draft.id?'PUT':'POST',{name:draft.name,kind:draft.kind,version:draft.version,content:draft.kind==='GROUP'?{customers:draft.customers}:draft.content});setDraft(null);})}>{t('Save','حفظ')}</button></div>}</DNDialog>;
}
