CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE TABLE settings (id integer PRIMARY KEY CHECK(id=1), data jsonb NOT NULL, version integer NOT NULL DEFAULT 1);
INSERT INTO settings VALUES (1,'{"companyName":"AMT Electric","companyArabic":"AMT للكهرباء","currency":"SAR","vat":"15","draftPrefix":"DR","quotePrefix":"QT","staffDiscount":"5","minimumVisible":false,"showMaxDiscount":false,"allowOfflineCache":false,"pdfUnitPrices":"BOTH","backupRetentionDays":14}',1);
CREATE TABLE roles (id text PRIMARY KEY, permissions text[] NOT NULL, max_discount numeric(9,6) NOT NULL CHECK(max_discount BETWEEN 0 AND 100));
CREATE TABLE users (id uuid PRIMARY KEY, username text NOT NULL UNIQUE, name text NOT NULL, password_hash text NOT NULL, role_id text NOT NULL REFERENCES roles(id), permissions text[] NOT NULL DEFAULT '{}', max_discount numeric(9,6), disabled boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE sessions (token_hash text PRIMARY KEY, user_id uuid NOT NULL REFERENCES users(id), csrf text NOT NULL, expires_at timestamptz NOT NULL);
CREATE INDEX ON sessions(user_id);
CREATE TABLE login_attempts (key text PRIMARY KEY, attempts integer NOT NULL, expires_at timestamptz NOT NULL);
CREATE TABLE brands (id uuid PRIMARY KEY, name text NOT NULL, normalized text UNIQUE NOT NULL, active boolean NOT NULL DEFAULT true, default_method text NOT NULL DEFAULT 'COST_MARKUP');
CREATE TABLE categories (id uuid PRIMARY KEY, name text NOT NULL, normalized text UNIQUE NOT NULL, active boolean NOT NULL DEFAULT true);
CREATE TABLE products (id uuid PRIMARY KEY, part_number text NOT NULL, normalized_part text NOT NULL UNIQUE, description text NOT NULL, brand_id uuid REFERENCES brands(id), category_id uuid REFERENCES categories(id), keywords text NOT NULL DEFAULT '', unit text NOT NULL DEFAULT 'pcs', quantity_precision integer NOT NULL CHECK(quantity_precision BETWEEN 0 AND 3), active boolean NOT NULL DEFAULT true, version integer NOT NULL DEFAULT 1, created_by uuid REFERENCES users(id), updated_by uuid REFERENCES users(id), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE product_pricing (product_id uuid PRIMARY KEY REFERENCES products(id), method text NOT NULL CHECK(method IN ('COST_MARKUP','LIST_DISCOUNT')), cost numeric(20,6) NOT NULL CHECK(cost>=0), markup numeric(20,6) NOT NULL CHECK(markup>=0), list_price numeric(20,6) NOT NULL CHECK(list_price>=0), base_discount numeric(9,6) NOT NULL CHECK(base_discount BETWEEN 0 AND 100), master_excl numeric(20,2) NOT NULL CHECK(master_excl>=0), vat numeric(9,6) NOT NULL CHECK(vat BETWEEN 0 AND 100), minimum_enabled boolean NOT NULL, minimum numeric(20,2) NOT NULL CHECK(minimum>=0), CHECK(NOT minimum_enabled OR minimum<=master_excl));
CREATE TABLE product_aliases (normalized text PRIMARY KEY, product_id uuid NOT NULL REFERENCES products(id), label text NOT NULL, kind text NOT NULL DEFAULT 'ALTERNATIVE');
CREATE INDEX ON product_aliases(product_id);
CREATE INDEX products_prefix ON products(normalized_part text_pattern_ops);
CREATE INDEX products_trgm ON products USING gin(normalized_part gin_trgm_ops);
CREATE INDEX products_description_trgm ON products USING gin(description gin_trgm_ops);
CREATE INDEX products_keywords_trgm ON products USING gin(keywords gin_trgm_ops);
CREATE INDEX products_brand ON products(brand_id);
CREATE INDEX products_category ON products(category_id);
CREATE TABLE customers (id uuid PRIMARY KEY, name text NOT NULL DEFAULT '', number text NOT NULL DEFAULT '', mobile text NOT NULL DEFAULT '', reference text NOT NULL DEFAULT '');
CREATE TABLE quotations (id uuid PRIMARY KEY, number text UNIQUE NOT NULL, status text NOT NULL CHECK(status IN ('DRAFT','ISSUED','DELETED')), owner_id uuid NOT NULL REFERENCES users(id), customer jsonb NOT NULL, lines jsonb NOT NULL, totals jsonb NOT NULL, version integer NOT NULL DEFAULT 1, company_snapshot jsonb, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), issued_at timestamptz);
CREATE INDEX ON quotations(owner_id,created_at DESC);
CREATE TABLE document_sequences (day text NOT NULL, kind text NOT NULL, counter integer NOT NULL, PRIMARY KEY(day,kind));
CREATE TABLE import_jobs (id uuid PRIMARY KEY, filename text NOT NULL, file_path text NOT NULL, kind text NOT NULL CHECK(kind IN ('EXCEL','PDF')), status text NOT NULL, owner_id uuid NOT NULL REFERENCES users(id), mapping jsonb NOT NULL DEFAULT '{}', defaults jsonb NOT NULL DEFAULT '{}', summary jsonb NOT NULL DEFAULT '{}', error text, version integer NOT NULL DEFAULT 1, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE import_rows (id uuid PRIMARY KEY, job_id uuid NOT NULL REFERENCES import_jobs(id), row_number integer NOT NULL, raw jsonb NOT NULL, proposed jsonb, errors jsonb NOT NULL DEFAULT '[]', duplicate_id uuid REFERENCES products(id), expected_version integer, decision text NOT NULL DEFAULT 'REVIEW', verified boolean NOT NULL DEFAULT false, confidence text NOT NULL DEFAULT 'HIGH', UNIQUE(job_id,row_number));
CREATE INDEX ON import_rows(job_id);
CREATE TABLE price_history (id uuid PRIMARY KEY, product_id uuid NOT NULL REFERENCES products(id), before_value jsonb, after_value jsonb NOT NULL, actor_id uuid REFERENCES users(id), source text NOT NULL, import_id uuid REFERENCES import_jobs(id), resulting_version integer NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX ON price_history(product_id,created_at DESC);
CREATE INDEX ON price_history(import_id);
CREATE TABLE audit_logs (id uuid PRIMARY KEY, actor_id uuid REFERENCES users(id), action text NOT NULL, entity text NOT NULL, entity_id text, before_value jsonb, after_value jsonb, reason text, created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX ON audit_logs(created_at DESC);
CREATE TABLE jobs (id uuid PRIMARY KEY, kind text NOT NULL, payload jsonb NOT NULL, status text NOT NULL DEFAULT 'PENDING', attempts integer NOT NULL DEFAULT 0, locked_at timestamptz, error text, created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX ON jobs(status,created_at);
CREATE TABLE backups (id uuid PRIMARY KEY, status text NOT NULL DEFAULT 'PENDING', filename text, size_bytes bigint, error text, requested_by uuid REFERENCES users(id), created_at timestamptz NOT NULL DEFAULT now(), completed_at timestamptz);
CREATE TABLE idempotency_keys (user_id uuid NOT NULL REFERENCES users(id), key text NOT NULL, response jsonb NOT NULL, PRIMARY KEY(user_id,key));
